db.juegos.drop()
db.juegos.insertMany([
    {_id: 1, nombre: "Mario Bros", fechaLanzamiento: new Date("1985-13-09"), precio: 49, modo: "multijugador", genero: ["aventura","plataformas"] },
    {_id: 2, nombre: "Resident Evil Village", fechaLanzamiento: new Date("2021-05-07"), precio: 53.99, modo: "Un jugador", genero: ["Survival Horror", "disparos"] },
    {_id: 3, nombre: "Far Cry 6", fechaLanzamiento: new Date("2021-10-6"), precio: 60, modo: "multijugador", genero: ["disparos en primera persona", "aventura"] },
    {_id: 4, nombre: "Far Cry 5", fechaLanzamiento: new Date("2018-3-26"), precio: 29.99, "Ubisoft Toronto", "Ubisoft Shanghai", "Ubisoft Kiev", "Red Storm"), modo: "multijugador", genero: ["disparos en primera persona", "aventura"] },
    {_id: 5, nombre: "Far Cry 4", fechaLanzamiento: new Date("2014-11-18"), precio: 29.99, modo: "multijugador", genero: ["disparos en primera persona", "aventura"] },
    {_id: 6, nombre: "Far Cry 2", fechaLanzamiento: new Date("2008-10-21"), precio: 10.98, modo: "multijugador", genero: ["disparos en primera persona", "aventura"]},
    {_id: 7, nombre: "Far Cry 3", fechaLanzamiento: new Date("2012-11-29"), precio: 19.9, modo: "multijugador", genero: ["disparos en primera persona", "aventura"] },
    {_id: 8, nombre: "Far Cry 1", fechaLanzamiento: new Date("2004-3-23"), precio: 9.99, modo: "multijugador", genero: ["disparos en primera persona", "aventura"] },
    {_id: 9, nombre: "Assassin's Creed Valhalla", fechaLanzamiento: new Date("2020-10-10"), precio: 39.95, modo: "Un jugador", genero: ["lucha", "aventura", "disparos", "plataformas"] },
    {_id: 10, nombre: "Life is Strange", fechaLanzamiento: new Date("2018-9-25"), precio: 19, modo: "Un jugador", genero: ["aventura gráfica", "acción", "aventura"] },
    {_id: 11, nombre: "Assassin's Creed: The Rebel Collection ", fechaLanzamiento: new Date("2019-12-6"), precio: 26.80, modo: "Un jugador", genero: ["lucha", "aventura", "disparos", "plataformas"] },
    {_id: 12, nombre: "Assassin's Creed III Remastered", fechaLanzamiento: new Date("2012-10-20"), precio: 39.95, modo: ("Un jugador", "multijugador"), genero: ["lucha", "aventura", "disparos", "plataformas"] },
    {_id: 13, nombre: "Assassin's Creed Odyssey", fechaLanzamiento: new Date("2018-10-1"), precio: 39.95, modo: "Un jugador", genero: ["lucha", "aventura", "disparos", "plataformas"]},
    {_id: 14, nombre: "Assassin's Creed Origins", fechaLanzamiento: new Date("2017-10-27"), precio: 29.95, modo: "Un jugador", genero: ["lucha", "aventura", "disparos", "plataformas"] },
    {_id: 15, nombre: "Assassin's Creed The Ezio Collection", fechaLanzamiento: new Date("2016-11-10"), precio: 19.95, modo: "Un jugador", genero: ["lucha", "aventura", "disparos", "plataformas"]  },
    {_id: 16, nombre: "Outlast2", fechaLanzamiento: new Date("2017-4-24"), precio: 29.99, modo: "Un jugador", genero: ["Survival horror", "independiente", "aventura"] },
    {_id: 17, nombre: "GTA V ", fechaLanzamiento: new Date("2013-7-17"), precio: 15.97, modo: ["multijugador", "Un jugador"], genero: ["accion", "aventura"] },
    {_id: 18, nombre: "Among Us", fechaLanzamiento: new Date("2018-6-15"), precio: 0, modo: "multijugador", genero: ["supervivencia", "accion"] },
    {_id: 19, nombre: "Pokemón Rojo", fechaLanzamiento: new Date("1996-2.27"), precio: 13, modo: ["Un jugador","multijugador"], genero: "J-rol" },
    {_id: 20, nombre: "Amnesia", fechaLanzamiento: new Date("2010-9-8"), precio: 19.99, modo: "Un juego", genero: ["independiente", "Survival horror", "aventura"] },
    {_id: 21, nombre: "Beyond Two Souls", fechaLanzamiento: new Date("2013-10-3"), precio: 14.95, modo: "Un jugador", genero: ["interactiva", "accion", "aventura"] },
    {_id: 22, nombre: "Life is Strange", fechaLanzamiento: new Date("2018-9-25"), precio: 19, modo: "Un jugador", genero: ["aventura", "accion"] },
    {_id: 23, nombre: "GTA San Andreas", fechaLanzamiento: new Date("2004-10-26"), precio: 19.95, modo: ["multijugador","Un jugador"], genero: ["accion", "aventura"] },
    {_id: 24, nombre: "Minecraft", fechaLanzamiento: new Date("2011-11-18"), precio: 6.95, modo: ["multijugador", "Un jugador"], genero: ["rol", "aventura", "arena"] },
    {_id: 25, nombre: "Left 4 Dead 2", fechaLanzamiento: new Date("2009-11-17"), precio: 8.19, modo: "multijugador", genero: "Survival horror" },
    {_id: 26, nombre: "COD", fechaLanzamiento: new Date("2003-10-29"), precio: 19, modo: "multijugador", genero: "disparos" },
    {_id: 27, nombre: "WatchDogs", fechaLanzamiento: new Date("2020-10-29"), precio: 19.95, modo: ["multijugador", "Un jugador"], genero: ["accion", "aventura"] },
])
